# GLOBAL VARIABLES
SESSION_TIMEOUT = 300
MAX_EVENT_SEARCH_TIME_RANGE = 3000000
NUM_OF_EVENTS_PER_PAGE = 10

MIN_USERNAME_LENGTH = 4
MAX_USERNAME_LENGTH = 32

PASSWORD_HASH_LENGTH = 64
SALT_LENGTH = 8
ENCRYPTED_PASSWORD_LENGTH = 88

MAX_EVENT_TITLE_LENGTH = 256
MAX_TAG_LENGTH = 256
